### PR TITLE
gray color

### PR DESCRIPTION
**Pull request by RobertMili**

### CODE REVIEW

**Comment by RobertMili** [comment]
Screenshot from 2023-10-19 08-53-12

**Comment by RobertMili** [comment]
Screenshot from 2023-10-23 15-57-19

**Review by safstromo — CHANGES_REQUESTED** [review]
We need dome media queries on this:
Screenshot from 2023-10-24 08-03-59

**Review by figgge — APPROVED** [review]
Perfect!

**Review by safstromo — APPROVED** [review]
Great :+1:

**Comment by safstromo** [comment]
[Grå linje på highscore hela vägen](https://trello.com/c/q9wREMIv/176-gr%C3%A5-linje-p%C3%A5-highscore-hela-v%C3%A4gen)

**Pull request merged**
