### PR TITLE
Add firstMapOne

### PR DESCRIPTION
**Pull request by RobertMili**
- addet map
- addet collides ( to player can't go throughwall )
- player can't go through objects.

### CODE REVIEW

**Comment by RobertMili** [comment]
Screenshot from 2023-10-11 16-55-50

**Review by safstromo — CHANGES_REQUESTED** [review]
waiting for update :)

**Comment by RobertMili** [comment]
Screenshot from 2023-10-12 14-10-51

**Review by safstromo — APPROVED** [review]
Great looking map! :+1:

**Pull request merged**
